### ISSUE TITLE
Drag and drop not working on firefox.

### ISSUE THREAD

**Issue by ilyaskarim** [froala/froala-pages#1]
#### Description
Page builder drag and drop feature doesn't work on firefox. When we drag a design block to the side of the page it views the image directly. 

##### Expected behavior.
Droping a design block to the side of the froala page demo it should show the design block.

##### Steps to reproduce the problem.

1. Goto https://froala.com/pages/demo/
2. Drag a design block from right and drop it on the left side of the demo.
3. Notice that it redirects to the image directly

##### OS.
Windows 10

##### Browser.
Firefox 74.0

##### Recording (if available)
![FroalaPages](https://user-images.githubusercontent.com/42450390/78818910-d6bb5500-79ee-11ea-9b28-da8879033cb0.gif)

#### Support Ticket link.
https://froala.zendesk.com/agent/tickets/18710

**Comment by kapil2704** [comment]
@ilyaskarim This has been resolved in v1.0.3
