### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by ghost** [froala/froala-pages#5]
It appears that Froala Pages does not support the Image Upload capability like Froala Editor does (https://froala.com/wysiwyg-editor/docs/concepts/image/upload/).  Will this functionality be available for Froala Pages soon?

**Comment by ghost** [comment]
@kapil2704 any updates on this issue?

**Comment by kapil2704** [comment]
Hi @miketkim It does provide this functionality to upload/change photos but it does not provide the functionality to change background images. You can design your own custom block and use as you want.

**Comment by ghost** [comment]
@kapil2704 Can you send me a link of documentation where Froala Pages supports this?  It does not seem to be on the Froala Pages documentation.
